type/ci:
  - .github/workflows/**/*
  - .github/actions/**/*
  - .github/**/*.yml
  - .github/**/*.json

type/documentation:
  - docs/**/*
  - .github/ISSUE_TEMPLATE/**/*
  - languages/**/docs/**/*

track/bash:
  - languages/bash/**/*

track/c:
  - languages/c/**/*

track/common-lisp:
  - languages/common-lisp/**/*

track/cpp:
  - languages/cpp/**/*

track/csharp:
  - languages/csharp/**/*

track/dart:
  - languages/dart/**/*

track/delphi:
  - languages/delphi/**/*

track/elixir:
  - languages/elixir/**/*

track/elm:
  - languages/elm/**/*

track/emacs-lisp:
  - languages/emacs-lisp/**/*

track/erlang:
  - languages/erlang/**/*

track/factor:
  - languages/factor/**/*

track/fsharp:
  - languages/fsharp/**/*

track/go:
  - languages/go/**/*

track/haskell:
  - languages/haskell/**/*

track/j:
  - languages/j/**/*

track/java:
  - languages/java/**/*

track/javascript:
  - languages/javascript/**/*

track/julia:
  - languages/julia/**/*

track/kotlin:
  - languages/kotlin/**/*

track/nim:
  - languages/nim/**/*

track/ocaml:
  - languages/ocaml/**/*

track/perl5:
  - languages/perl5/**/*

track/pharo-smalltalk:
  - languages/pharo-smalltalk/**/*

track/purescript:
  - languages/purescript/**/*

track/python:
  - languages/python/**/*

track/r:
  - languages/r/**/*

track/raku:
  - languages/raku/**/*

track/racket:
  - languages/racket/**/*

track/reasonml:
  - languages/reasonml/**/*

track/ruby:
  - languages/ruby/**/*

track/rust:
  - languages/rust/**/*

track/scala:
  - languages/scala/**/*

track/scheme:
  - languages/scheme/**/*

track/swift:
  - languages/swift/**/*

track/typescript:
  - languages/typescript/**/*

track/x86-64-assembly:
  - languages/x86-64-assembly/**/*
