name: Gradle Compilability CI

on:
  push:
    paths:
      - 'languages/java/exercises/concept/**/*.java'
      - 'languages/java/exercises/practice/**/*.java'
  pull_request:
    paths:
      - 'languages/java/exercises/concept/**/*.java'
      - 'languages/java/exercises/practice/**/*.java'

jobs:
  check-compilation-pr:
    runs-on: ubuntu-latest

    if: ${{ github.event_name == 'pull_request' }}

    steps:
      - uses: actions/checkout@v2

      - name: Number of commits since beginning of PR
        id: number_of_commits
        run: |
          echo "::set-output name=number::$(git log ${{ github.event.pull_request.base.sha }}..${{ github.sha }}  --pretty=oneline | wc -l)"
        shell: bash

      - uses: actions/checkout@v2
        with:
          fetch-depth: ${{ steps.number_of_commits.outputs.number }}

      - name: Retrieve changed files (PR)
        id: getfiles
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --diff-filter=d --name-only -r ${{ github.event.pull_request.base.sha }}  ${{ github.sha }} | grep \\.nim | xargs)"
        shell: bash

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Check that each file compiles with `gradle check`
        run: |
          set +e

          exitCode=0
          for file in ${{ steps.getfiles.outputs.files }}
          do
              gradle check $file
              exitCode=$((exitCode + $?))
          done
          exit $exitCode
        shell: bash

  check-compilation-push:
    runs-on: ubuntu-latest

    if: ${{ github.event_name == 'push' }}

    steps:
      - uses: actions/checkout@v2

      - name: Number of commits since last push
        id: number_of_commits
        run: |
          echo "::set-output name=number::$(git log ${{ github.event.before }}..${{ github.sha }}  --pretty=oneline | wc -l)"
        shell: bash

      - uses: actions/checkout@v2
        with:
          fetch-depth: ${{ steps.number_of_commits.outputs.number }}

      - name: Retrieve changed files (push)
        id: getfiles
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --diff-filter=d --name-only -r ${{ github.event.before }}  ${{ github.sha }} | grep \\.nim | xargs)"
        shell: bash

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Check that each file compiles with `gradle check`
        run: |
          set +e

          exitCode=0
          for file in ${{ steps.getfiles.outputs.files }}
          do
              gradle check $file
              exitCode=$((exitCode + $?))
          done
          exit $exitCode
        shell: bash
