name: Julia CI

on:
  push:
    paths:
    - '**.jl'
    - 'languages/julia/**'
  pull_request:
    paths:
    - '**.jl'
    - 'languages/julia/**'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1.0', '1.1', '1.2', '1.3', nightly]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
      - uses: actions/checkout@v1.0.0

      - name: "Set up Julia ${{ matrix.julia-version }}"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}

      - name: Test exercises
        run: |
          cd languages/julia/
          julia --color=yes runtests.jl
        shell: bash
